version: '3.8'

services:
  spring-backend:
    build:
      context: .
      dockerfile: spring-backend/Dockerfile
    container_name: spring-backend
    ports:
      - "8080:8080"
    networks:
      - app

  node-server:
    build:
      context: .
      dockerfile: node-server/Dockerfile
    container_name: node-server
    ports:
      - "3000:3000"
    depends_on:
      - spring-backend
    environment:
      - BACKEND_API=http://spring-backend:8080
    networks:
      - app

networks:
  app:
    driver: bridge
    name: app